### PR TITLE
fix: avoid strnlen() in cs_strndup for Mac OS X 10.5 portability

### LINKED ISSUE #2517: Usage of non-portable strndup in cstest
### Work environment

| Questions                                | Answers
|------------------------------------------|--------------------
| OS/arch/bits                             | Mac OS X 10.5
| Architecture                             | powerpc
| Source of Capstone                       | Source with `-DCAPSTONE_BUILD_CSTEST=ON`
| Version/git commit                       | next, 5bd05e34245eeca7833d30b677131cab6ea7a6fa

### Expected behavior

cstest (`-DCAPSTONE_BUILD_CSTEST=ON`) compiles

### Actual behavior
```
[98/175] Building C object suite/cstest/CMakeFiles/libcstest.dir/src/helper.c.o
FAILED: suite/cstest/CMakeFiles/libcstest.dir/src/helper.c.o
/opt/local/bin/gcc-mp-7 -DCAPSTONE_AARCH64_SUPPORT -DCAPSTONE_ALPHA_SUPPORT -DCAPSTONE_ARM_SUPPORT -DCAPSTONE_BPF_SUPPORT -DCAPSTONE_DEBUG -DCAPSTONE_EVM_SUPPORT -DCAPSTONE_HAS_AARCH64 -DCAPSTONE_HAS_ALPHA -DCAPSTONE_HAS_ARM -DCAPSTONE_HAS_BPF -DCAPSTONE_HAS_EVM -DCAPSTONE_HAS_HPPA -DCAPSTONE_HAS_LOONGARCH -DCAPSTONE_HAS_M680X -DCAPSTONE_HAS_M68K -DCAPSTONE_HAS_MIPS -DCAPSTONE_HAS_MOS65XX -DCAPSTONE_HAS_POWERPC -DCAPSTONE_HAS_RISCV -DCAPSTONE_HAS_SH -DCAPSTONE_HAS_SPARC -DCAPSTONE_HAS_SYSTEMZ -DCAPSTONE_HAS_TMS320C64X -DCAPSTONE_HAS_TRICORE -DCAPSTONE_HAS_WASM -DCAPSTONE_HAS_X86 -DCAPSTONE_HAS_XCORE -DCAPSTONE_HAS_XTENSA -DCAPSTONE_HPPA_SUPPORT -DCAPSTONE_LOONGARCH_SUPPORT -DCAPSTONE_M680X_SUPPORT -DCAPSTONE_M68K_SUPPORT -DCAPSTONE_MIPS_SUPPORT -DCAPSTONE_MOS65XX_SUPPORT -DCAPSTONE_PPC_SUPPORT -DCAPSTONE_RISCV_SUPPORT -DCAPSTONE_SH_SUPPORT -DCAPSTONE_SPARC_SUPPORT -DCAPSTONE_SYSTEMZ_SUPPORT -DCAPSTONE_TMS320C64X_SUPPORT -DCAPSTONE_TRICORE_SUPPORT -DCAPSTONE_USE_SYS_DYN_MEM -DCAPSTONE_WASM_SUPPORT -DCAPSTONE_X86_SUPPORT -DCAPSTONE_XCORE_SUPPORT -DCAPSTONE_XTENSA_SUPPORT -I"/Users/florian/dev/capstone/include>" -I/Users/florian/dev/capstone/suite/cstest/include -I/Users/florian/dev/capstone/build/suite/cstest/extern/src/cmocka_ext/include -I/Users/florian/dev/capstone/build/suite/cstest/extern/src/libcyaml_ext/include -I/Users/florian/dev/capstone/include -g -Werror -Wall -Warray-bounds -Wshift-negative-value -Wreturn-type -Wformat -Wmissing-braces -Wunused-function -Wunused-variable -Wparentheses -Wint-in-bool-context -Wmisleading-indentation -Wno-maybe-uninitialized -Wshadow=local -MD -MT suite/cstest/CMakeFiles/libcstest.dir/src/helper.c.o -MF suite/cstest/CMakeFiles/libcstest.dir/src/helper.c.o.d -o suite/cstest/CMakeFiles/libcstest.dir/src/helper.c.o -c /Users/florian/dev/capstone/suite/cstest/src/helper.c
/Users/florian/dev/capstone/suite/cstest/src/helper.c: In function 'replace_hex':
/Users/florian/dev/capstone/suite/cstest/src/helper.c:55:13: error: implicit declaration of function 'strndup' [-Werror=implicit-function-declaration]
   tmp_tmp = strndup(tmp, orig_found - tmp);
             ^~~~~~~
/Users/florian/dev/capstone/suite/cstest/src/helper.c:55:13: error: incompatible implicit declaration of built-in function 'strndup' [-Werror]
/Users/florian/dev/capstone/suite/cstest/src/helper.c: In function 'replace_negative':
/Users/florian/dev/capstone/suite/cstest/src/helper.c:120:13: error: incompatible implicit declaration of built-in function 'strndup' [-Werror]
   tmp_tmp = strndup(tmp, orig_found - tmp);
             ^~~~~~~
cc1: all warnings being treated as errors
[100/175] Linking C static library libcapstone.a
ninja: build stopped: subcommand failed.
```

### Steps to reproduce the behavior

Compile with cmake and cstest enabled (`-DCAPSTONE_BUILD_CSTEST=ON`) on a platform that does not have strndup.

### Additional Logs, screenshots, source code,  configuration dump, ...

There are two usages of `strndup` which is specified by POSIX, but not C standard, and thus not widely available, e.g. on Mac OS X 10.5 with gcc 7. On this platform, https://github.com/capstone-engine/capstone/pull/2508 is also necessary for cstest.

### PR DESCRIPTION
**Pull request by Scottcjn**
Fixes #2517

The cs_strndup() function in cstest uses strnlen(), which is a POSIX.1-2008 addition and is not available on older platforms -- in our case Mac OS X 10.5 Leopard on PowerPC (we build on a Power Mac G4).

This just replaces the strnlen() call with a plain loop that does the same bounded-length scan. No functional change, just makes it compile on systems that lack strnlen.

Tested building cstest with -DCAPSTONE_BUILD_CSTEST=ON on Leopard.

### CODE REVIEW

**Comment by Rot127** [comment]
Thanks. Can you please implement it as `cs_strnlen` in `util.c` though?
Good chance we need it again in the future.

**Comment by Scottcjn** [comment]
Done — extracted the loop into `cs_strnlen()` in `utils.c` with declaration in `utils.h`. Also declared it in `helper.h` so the test suite can call it (since `utils.h` is not on the cstest include path). `cs_strndup` in `helper.c` now calls `cs_strnlen` instead of inlining the loop. Ready for re-review.

File: suite/cstest/include/helper.h [hunk 1]
```diff
@@ -19,4 +19,8 @@ void norm_spaces(char *str);
 void str_to_lower(char *str);
 char *cs_strndup(const char *s, size_t n);
 
+// Provided by libcapstone (utils.c). Portable strnlen replacement
+// for platforms that lack it.
+size_t cs_strnlen(const char *str, size_t n);
+
```
Comment (Rot127) [inline suite/cstest/include/helper.h]: You can include `#include "../../../utils.h"` here instead.

File: utils.c [hunk 2]
```diff
@@ -47,6 +47,18 @@ char *cs_strdup(const char *str)
 	return (char *)memmove(new, str, len);
 }
 
+// Portable strnlen replacement for platforms that lack it
+// (e.g. Mac OS X 10.5 Leopard).
+size_t cs_strnlen(const char *str, size_t n)
+{
+	size_t l = 0;
+
+	while (l < n && str[l] != '\0')
```
Comment (Rot127) [inline utils.c:59]: Check for NULL

**Review by Rot127 — CHANGES_REQUESTED** [review]

File: suite/cstest/include/helper.h [hunk 3]
```diff
@@ -19,4 +19,8 @@ void norm_spaces(char *str);
 void str_to_lower(char *str);
 char *cs_strndup(const char *s, size_t n);
 
+// Provided by libcapstone (utils.c). Portable strnlen replacement
+// for platforms that lack it.
+#include "../../../utils.h"
```
Comment (Rot127) [inline suite/cstest/include/helper.h]: Move this to the other includes.

**Review by Rot127 — CHANGES_REQUESTED** [review]

File: suite/cstest/include/helper.h (hunk 3 above)
Comment (Rot127) [reply suite/cstest/include/helper.h]: Also, remove the comment.

**Comment by Scottcjn** [comment]
Addressed all 4 review comments:
1. `helper.h` now includes `utils.h` instead of redeclaring `cs_strnlen`
2. Added NULL check in `cs_strnlen()`
3. Include moved to the other includes group
4. Removed the explanatory comment

Ready for another look, @Rot127.

**Review by Rot127 — APPROVED** [review]

**Comment by Scottcjn** [comment]
@Rot127 All 4 review comments addressed — cs_strnlen extracted to utils.c, NULL check added, helper.h includes utils.h, strnlen fallback uses cs_strnlen. Ready for re-review when you get a chance. Thanks!
