### PR TITLE
HPPA dissassembler fix unitialized variables errors

### LINKED ISSUE #2304: HPPADisassembler.c unitialized variables
@R33v0LT take a look please:
```
../subprojects/capstone-next/arch/HPPA/HPPADisassembler.c:2505:2: error: variable 'sop' is used uninitialized whenever switch default is taken [-Werror,-Wsometimes-uninitialized]
        default:
        ^~~~~~~
../subprojects/capstone-next/arch/HPPA/HPPADisassembler.c:2508:30: note: uninitialized use occurs here
        push_int_modifier(hppa_ext, sop);
                                    ^~~
../subprojects/capstone-next/arch/HPPA/HPPADisassembler.c:2486:14: note: initialize the variable 'sop' to silence this warning
        uint32_t sop;
                    ^
                     = 0
../subprojects/capstone-next/arch/HPPA/HPPADisassembler.c:2836:15: error: variable 'subop' is used uninitialized whenever 'if' condition is false [-Werror,-Wsometimes-uninitialized]
                        } else if (class == 3) {
                                   ^~~~~~~~~~
../subprojects/capstone-next/arch/HPPA/HPPADisassembler.c:2846:12: note: uninitialized use occurs here
                                       subop, ud->mode);
                                       ^~~~~
../subprojects/capstone-next/arch/HPPA/HPPADisassembler.c:2836:11: note: remove the 'if' if its condition is always true
                        } else if (class == 3) {
                               ^~~~~~~~~~~~~~~~
../subprojects/capstone-next/arch/HPPA/HPPADisassembler.c:2794:16: note: initialize the variable 'subop' to silence this warning
        uint32_t subop;
                      ^
                       = 0
2 errors generated.
```
See https://github.com/rizinorg/rizin/actions/runs/8480023715/job/23235014043?pr=4394#step:13:748 for more details

### PR DESCRIPTION
**Pull request by R33v0LT**
**Your checklist for this pull request**
- [x] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [x] I've added tests that prove my fix is effective or that my feature works (if possible)

**Detailed description**

This PR fixes errors like `unitialized variables` when using clang with flags `-Wall -Winvalid-pch -Werror -O3 --std=gnu99 -Werror=sizeof-pointer-memaccess`

**Test plan**

- [x] Make all CI tests successful

**Closing issues**

closes #2304

### CODE REVIEW

File: cstool/cstool_hppa.c [hunk 1]
```diff
@@ -21,6 +21,8 @@ void print_insn_detail_hppa(csh handle, cs_insn *ins)
 		cs_hppa_op *op = &(hppa->operands[i]);
 		uint64_t target_addr;
 		switch (op->type) {
+		case HPPA_OP_INVALID:
```
Comment (Rot127) [inline cstool/cstool_hppa.c]: Please add a `default` case before.

**Review by Rot127 — CHANGES_REQUESTED** [review]

**Comment by Rot127** [comment]
Also, please fill out the complete PR description (I update it for you). We have stricter requirements now.
In your case for testing `CI green` is enough for me.

**Review by Rot127 — APPROVED** [review]

**Review by kabeor — APPROVED** [review]

**Comment by kabeor** [comment]
Thank you!
