### PR TITLE
Fix SH build warnings.

### LINKED ISSUE #2010: sh warnings
```
: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {0, SH_REG_SR, ISA_ALL, none},
arch/SH/SHDisassembler.c:147:7: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {1, SH_REG_GBR, ISA_ALL, none},
arch/SH/SHDisassembler.c:148:7: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {2, SH_REG_VBR, ISA_ALL, none},
arch/SH/SHDisassembler.c:149:7: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {3, SH_REG_SSR, ISA_SH3, none},
arch/SH/SHDisassembler.c:150:7: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {4, SH_REG_SPC, ISA_SH3, none},
arch/SH/SHDisassembler.c:151:7: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {5, SH_REG_MOD, ISA_ALL, shdsp},
arch/SH/SHDisassembler.c:152:7: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {6, SH_REG_RS, ISA_ALL, shdsp},
arch/SH/SHDisassembler.c:153:7: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {7, SH_REG_RE, ISA_ALL, shdsp},
arch/SH/SHDisassembler.c:154:7: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {8, SH_REG_R0_BANK, ISA_SH3, none},
arch/SH/SHDisassembler.c:155:7: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {9, SH_REG_R1_BANK, ISA_SH3, none},
arch/SH/SHDisassembler.c:156:8: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {10, SH_REG_R2_BANK, ISA_SH3, none},
arch/SH/SHDisassembler.c:157:8: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {11, SH_REG_R3_BANK, ISA_SH3, none},
arch/SH/SHDisassembler.c:158:8: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {12, SH_REG_R4_BANK, ISA_SH3, none},
arch/SH/SHDisassembler.c:159:8: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {13, SH_REG_R5_BANK, ISA_SH3, none},
arch/SH/SHDisassembler.c:160:8: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {14, SH_REG_R6_BANK, ISA_SH3, none},
arch/SH/SHDisassembler.c:161:8: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {15, SH_REG_R7_BANK, ISA_SH3, none},
arch/SH/SHDisassembler.c:162:8: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {-1, SH_REG_INVALID, ISA_ALL, none},
arch/SH/SHDisassembler.c:224:7: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {0, SH_INS_BSRF, ISA_SH2, none},
arch/SH/SHDisassembler.c:225:7: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {2, SH_INS_BRAF, ISA_SH2, none},
arch/SH/SHDisassembler.c:226:7: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {6, SH_INS_MOVLI, ISA_SH4A, none},
arch/SH/SHDisassembler.c:227:7: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {7, SH_INS_MOVCO, ISA_SH4A, none},
                    ^~~~~~~~~~~~
                    {           }
arch/SH/SHDisassembler.c:228:7: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {8, SH_INS_PREF, ISA_SH2A, none},
arch/SH/SHDisassembler.c:229:7: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {9, SH_INS_OCBI, ISA_SH4, none},
arch/SH/SHDisassembler.c:230:8: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {10, SH_INS_OCBP, ISA_SH4, none},
arch/SH/SHDisassembler.c:231:8: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {11, SH_INS_OCBWB, ISA_SH4, none},
arch/SH/SHDisassembler.c:232:8: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {12, SH_INS_MOVCA, ISA_SH4, none},
arch/SH/SHDisassembler.c:233:8: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {13, SH_INS_PREFI, ISA_SH4A, none},
arch/SH/SHDisassembler.c:234:8: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {14, SH_INS_ICBI, ISA_SH4A, none},
arch/SH/SHDisassembler.c:235:8: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {-1, SH_INS_INVALID, ISA_ALL, none},
arch/SH/SHDisassembler.c:235:8: warning: implicit conversion from enumeration type 'enum sh_insn' to different enumeration type 'sh_reg' [-Wenum-conversion]
                {-1, SH_INS_INVALID, ISA_ALL, none},
arch/SH/SHDisassembler.c:234:8: warning: implicit conversion from enumeration type 'enum sh_insn' to different enumeration type 'sh_reg' [-Wenum-conversion]
                {14, SH_INS_ICBI, ISA_SH4A, none},
arch/SH/SHDisassembler.c:233:8: warning: implicit conversion from enumeration type 'enum sh_insn' to different enumeration type 'sh_reg' [-Wenum-conversion]
                {13, SH_INS_PREFI, ISA_SH4A, none},
arch/SH/SHDisassembler.c:232:8: warning: implicit conversion from enumeration type 'enum sh_insn' to different enumeration type 'sh_reg' [-Wenum-conversion]
                {12, SH_INS_MOVCA, ISA_SH4, none},
arch/SH/SHDisassembler.c:231:8: warning: implicit conversion from enumeration type 'enum sh_insn' to different enumeration type 'sh_reg' [-Wenum-conversion]
                {11, SH_INS_OCBWB, ISA_SH4, none},
arch/SH/SHDisassembler.c:230:8: warning: implicit conversion from enumeration type 'enum sh_insn' to different enumeration type 'sh_reg' [-Wenum-conversion]
                {10, SH_INS_OCBP, ISA_SH4, none},
arch/SH/SHDisassembler.c:229:7: warning: implicit conversion from enumeration type 'enum sh_insn' to different enumeration type 'sh_reg' [-Wenum-conversion]
                {9, SH_INS_OCBI, ISA_SH4, none},
                    ^~~~~~~~~~~
arch/SH/SHDisassembler.c:228:7: warning: implicit conversion from enumeration type 'enum sh_insn' to different enumeration type 'sh_reg' [-Wenum-conversion]
                {8, SH_INS_PREF, ISA_SH2A, none},
arch/SH/SHDisassembler.c:227:7: warning: implicit conversion from enumeration type 'enum sh_insn' to different enumeration type 'sh_reg' [-Wenum-conversion]
                {7, SH_INS_MOVCO, ISA_SH4A, none},
arch/SH/SHDisassembler.c:226:7: warning: implicit conversion from enumeration type 'enum sh_insn' to different enumeration type 'sh_reg' [-Wenum-conversion]
                {6, SH_INS_MOVLI, ISA_SH4A, none},
arch/SH/SHDisassembler.c:225:7: warning: implicit conversion from enumeration type 'enum sh_insn' to different enumeration type 'sh_reg' [-Wenum-conversion]
                {2, SH_INS_BRAF, ISA_SH2, none},
arch/SH/SHDisassembler.c:224:7: warning: implicit conversion from enumeration type 'enum sh_insn' to different enumeration type 'sh_reg' [-Wenum-conversion]
                {0, SH_INS_BSRF, ISA_SH2, none},
arch/SH/SHDisassembler.c:237:17: warning: implicit conversion from enumeration type 'sh_insn' (aka 'enum sh_insn') to different enumeration type 'enum lookup_type' [-Wenum-conversion]
        sh_insn insn = lookup_insn(list, insn_code, mode);
arch/SH/SHDisassembler.c:187:45: note: expanded from macro 'lookup_insn'
#define lookup_insn(list, no, mode) (lookup(insn, list, no, mode).insn)
arch/SH/SHDisassembler.c:237:17: warning: variable 'insn' is uninitialized when used within its own initialization [-Wuninitialized]
        sh_insn insn = lookup_insn(list, insn_code, mode);
arch/SH/SHDisassembler.c:187:45: note: expanded from macro 'lookup_insn'
#define lookup_insn(list, no, mode) (lookup(insn, list, no, mode).insn)
arch/SH/SHDisassembler.c:364:7: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {0, SH_INS_CLRT, ISA_ALL, none},
arch/SH/SHDisassembler.c:365:7: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {1, SH_INS_SETT, ISA_ALL, none},
arch/SH/SHDisassembler.c:366:7: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {2, SH_INS_CLRMAC, ISA_ALL, none},
arch/SH/SHDisassembler.c:367:7: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {3, SH_INS_LDTLB, ISA_SH3, none},
arch/SH/SHDisassembler.c:368:7: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {4, SH_INS_CLRS, ISA_SH3, none},
arch/SH/SHDisassembler.c:369:7: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {5, SH_INS_SETS, ISA_SH3, none},
arch/SH/SHDisassembler.c:370:7: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {6, SH_INS_NOTT, -(ISA_SH2A), none},
arch/SH/SHDisassembler.c:371:7: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {8, SH_INS_CLRDMXY, ISA_SH4A, shdsp},
arch/SH/SHDisassembler.c:372:7: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {9, SH_INS_SETDMX, ISA_SH4A, shdsp},
arch/SH/SHDisassembler.c:373:8: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {12, SH_INS_SETDMY, ISA_SH4A, shdsp},
arch/SH/SHDisassembler.c:374:8: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {-1, SH_INS_INVALID, ISA_ALL, none},
arch/SH/SHDisassembler.c:374:8: warning: implicit conversion from enumeration type 'enum sh_insn' to different enumeration type 'sh_reg' [-Wenum-conversion]
                {-1, SH_INS_INVALID, ISA_ALL, none},
arch/SH/SHDisassembler.c:373:8: warning: implicit conversion from enumeration type 'enum sh_insn' to different enumeration type 'sh_reg' [-Wenum-conversion]
                {12, SH_INS_SETDMY, ISA_SH4A, shdsp},
arch/SH/SHDisassembler.c:372:7: warning: implicit conversion from enumeration type 'enum sh_insn' to different enumeration type 'sh_reg' [-Wenum-conversion]
                {9, SH_INS_SETDMX, ISA_SH4A, shdsp},
arch/SH/SHDisassembler.c:371:7: warning: implicit conversion from enumeration type 'enum sh_insn' to different enumeration type 'sh_reg' [-Wenum-conversion]
                {8, SH_INS_CLRDMXY, ISA_SH4A, shdsp},
arch/SH/SHDisassembler.c:370:7: warning: implicit conversion from enumeration type 'enum sh_insn' to different enumeration type 'sh_reg' [-Wenum-conversion]
                {6, SH_INS_NOTT, -(ISA_SH2A), none},
arch/SH/SHDisassembler.c:369:7: warning: implicit conversion from enumeration type 'enum sh_insn' to different enumeration type 'sh_reg' [-Wenum-conversion]
                {5, SH_INS_SETS, ISA_SH3, none},
arch/SH/SHDisassembler.c:368:7: warning: implicit conversion from enumeration type 'enum sh_insn' to different enumeration type 'sh_reg' [-Wenum-conversion]
                {4, SH_INS_CLRS, ISA_SH3, none},
arch/SH/SHDisassembler.c:367:7: warning: implicit conversion from enumeration type 'enum sh_insn' to different enumeration type 'sh_reg' [-Wenum-conversion]
                {3, SH_INS_LDTLB, ISA_SH3, none},
arch/SH/SHDisassembler.c:366:7: warning: implicit conversion from enumeration type 'enum sh_insn' to different enumeration type 'sh_reg' [-Wenum-conversion]
                {2, SH_INS_CLRMAC, ISA_ALL, none},
arch/SH/SHDisassembler.c:365:7: warning: implicit conversion from enumeration type 'enum sh_insn' to different enumeration type 'sh_reg' [-Wenum-conversion]
                {1, SH_INS_SETT, ISA_ALL, none},
arch/SH/SHDisassembler.c:364:7: warning: implicit conversion from enumeration type 'enum sh_insn' to different enumeration type 'sh_reg' [-Wenum-conversion]
                {0, SH_INS_CLRT, ISA_ALL, none},
arch/SH/SHDisassembler.c:377:17: warning: implicit conversion from enumeration type 'sh_insn' (aka 'enum sh_insn') to different enumeration type 'enum lookup_type' [-Wenum-conversion]
        sh_insn insn = lookup_insn(list, insn_code, mode);
arch/SH/SHDisassembler.c:187:45: note: expanded from macro 'lookup_insn'
#define lookup_insn(list, no, mode) (lookup(insn, list, no, mode).insn)
arch/SH/SHDisassembler.c:377:17: warning: variable 'insn' is uninitialized when used within its own initialization [-Wuninitialized]
        sh_insn insn = lookup_insn(list, insn_code, mode);
arch/SH/SHDisassembler.c:187:45: note: expanded from macro 'lookup_insn'
#define lookup_insn(list, no, mode) (lookup(insn, list, no, mode).insn)
arch/SH/SHDisassembler.c:395:7: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {0, SH_INS_NOP, ISA_ALL, none},
arch/SH/SHDisassembler.c:396:7: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {1, SH_INS_DIV0U, ISA_ALL, none},
arch/SH/SHDisassembler.c:397:7: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {2, SH_INS_MOVT, ISA_ALL, none},
arch/SH/SHDisassembler.c:398:7: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {3, SH_INS_MOVRT, -(ISA_SH2A), none},
arch/SH/SHDisassembler.c:399:8: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {-1, SH_INS_INVALID, ISA_ALL, none},
arch/SH/SHDisassembler.c:399:8: warning: implicit conversion from enumeration type 'enum sh_insn' to different enumeration type 'sh_reg' [-Wenum-conversion]
                {-1, SH_INS_INVALID, ISA_ALL, none},
arch/SH/SHDisassembler.c:398:7: warning: implicit conversion from enumeration type 'enum sh_insn' to different enumeration type 'sh_reg' [-Wenum-conversion]
                {3, SH_INS_MOVRT, -(ISA_SH2A), none},
arch/SH/SHDisassembler.c:397:7: warning: implicit conversion from enumeration type 'enum sh_insn' to different enumeration type 'sh_reg' [-Wenum-conversion]
                {2, SH_INS_MOVT, ISA_ALL, none},
arch/SH/SHDisassembler.c:396:7: warning: implicit conversion from enumeration type 'enum sh_insn' to different enumeration type 'sh_reg' [-Wenum-conversion]
                {1, SH_INS_DIV0U, ISA_ALL, none},
arch/SH/SHDisassembler.c:395:7: warning: implicit conversion from enumeration type 'enum sh_insn' to different enumeration type 'sh_reg' [-Wenum-conversion]
                {0, SH_INS_NOP, ISA_ALL, none},
arch/SH/SHDisassembler.c:401:17: warning: implicit conversion from enumeration type 'sh_insn' (aka 'enum sh_insn') to different enumeration type 'enum lookup_type' [-Wenum-conversion]
        sh_insn insn = lookup_insn(list, insn_code, mode);
arch/SH/SHDisassembler.c:187:45: note: expanded from macro 'lookup_insn'
#define lookup_insn(list, no, mode) (lookup(insn, list, no, mode).insn)
arch/SH/SHDisassembler.c:401:17: warning: variable 'insn' is uninitialized when used within its own initialization [-Wuninitialized]
        sh_insn insn = lookup_insn(list, insn_code, mode);
arch/SH/SHDisassembler.c:187:45: note: expanded from macro 'lookup_insn'
#define lookup_insn(list, no, mode) (lookup(insn, list, no, mode).insn)
arch/SH/SHDisassembler.c:419:6: warning: suggest braces around initialization of subobject [-Wmissing-braces]
        {0, SH_REG_MACH, ISA_ALL, none},
arch/SH/SHDisassembler.c:420:6: warning: suggest braces around initialization of subobject [-Wmissing-braces]
        {1, SH_REG_MACL, ISA_ALL, none},
arch/SH/SHDisassembler.c:421:6: warning: suggest braces around initialization of subobject [-Wmissing-braces]
        {2, SH_REG_PR, ISA_ALL, none},
arch/SH/SHDisassembler.c:422:6: warning: suggest braces around initialization of subobject [-Wmissing-braces]
        {3, SH_REG_SGR, ISA_SH4, none},
arch/SH/SHDisassembler.c:423:6: warning: suggest braces around initialization of subobject [-Wmissing-braces]
        {4, SH_REG_TBR, -(ISA_SH2A), none},
arch/SH/SHDisassembler.c:424:6: warning: suggest braces around initialization of subobject [-Wmissing-braces]
        {5, SH_REG_FPUL, ISA_ALL, shfpu},
arch/SH/SHDisassembler.c:425:6: warning: suggest braces around initialization of subobject [-Wmissing-braces]
        {6, SH_REG_FPSCR, ISA_ALL, shfpu},
arch/SH/SHDisassembler.c:426:6: warning: suggest braces around initialization of subobject [-Wmissing-braces]
        {6, SH_REG_DSP_DSR, ISA_ALL, shdsp},
arch/SH/SHDisassembler.c:427:6: warning: suggest braces around initialization of subobject [-Wmissing-braces]
        {7, SH_REG_DSP_A0, ISA_ALL, shdsp},
arch/SH/SHDisassembler.c:428:6: warning: suggest braces around initialization of subobject [-Wmissing-braces]
        {8, SH_REG_DSP_X0, ISA_ALL, shdsp},
arch/SH/SHDisassembler.c:429:6: warning: suggest braces around initialization of subobject [-Wmissing-braces]
        {9, SH_REG_DSP_X1, ISA_ALL, shdsp},
arch/SH/SHDisassembler.c:430:7: warning: suggest braces around initialization of subobject [-Wmissing-braces]
        {10, SH_REG_DSP_Y0, ISA_ALL, shdsp},
arch/SH/SHDisassembler.c:431:7: warning: suggest braces around initialization of subobject [-Wmissing-braces]
        {11, SH_REG_DSP_Y1, ISA_ALL, shdsp},
arch/SH/SHDisassembler.c:432:7: warning: suggest braces around initialization of subobject [-Wmissing-braces]
        {15, SH_REG_DBR, ISA_SH4, none},
arch/SH/SHDisassembler.c:433:7: warning: suggest braces around initialization of subobject [-Wmissing-braces]
        {-1, SH_REG_INVALID, ISA_ALL, none},
arch/SH/SHDisassembler.c:444:8: warning: implicit conversion from enumeration type 'sh_reg' to different enumeration type 'enum lookup_type' [-Wenum-conversion]
        reg = lookup_regs(sts_lds_regs, s, mode);
arch/SH/SHDisassembler.c:186:45: note: expanded from macro 'lookup_regs'
#define lookup_regs(list, no, mode) (lookup(reg, list, no, mode).reg)
arch/SH/SHDisassembler.c:444:8: warning: variable 'reg' is uninitialized when used here [-Wuninitialized]
        reg = lookup_regs(sts_lds_regs, s, mode);
arch/SH/SHDisassembler.c:186:45: note: expanded from macro 'lookup_regs'
#define lookup_regs(list, no, mode) (lookup(reg, list, no, mode).reg)
arch/SH/SHDisassembler.c:441:2: note: variable 'reg' is declared here
        sh_reg reg;
        ^
arch/SH/SHDisassembler.c:476:7: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {0, SH_INS_RTS, ISA_ALL, none},
arch/SH/SHDisassembler.c:477:7: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {1, SH_INS_SLEEP, ISA_ALL, none},
arch/SH/SHDisassembler.c:478:7: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {2, SH_INS_RTE, ISA_ALL, none},
arch/SH/SHDisassembler.c:479:7: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {5, SH_INS_RESBANK, -(ISA_SH2A), none},
arch/SH/SHDisassembler.c:480:7: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {6, SH_INS_RTS_N, -(ISA_SH2A), none},
arch/SH/SHDisassembler.c:481:7: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {7, SH_INS_RTV_N, -(ISA_SH2A), none},
arch/SH/SHDisassembler.c:482:8: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {10, SH_INS_SYNCO, -(ISA_SH4A), none},
arch/SH/SHDisassembler.c:483:8: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {-1, SH_INS_INVALID, ISA_ALL, none},
arch/SH/SHDisassembler.c:483:8: warning: implicit conversion from enumeration type 'enum sh_insn' to different enumeration type 'sh_reg' [-Wenum-conversion]
                {-1, SH_INS_INVALID, ISA_ALL, none},
arch/SH/SHDisassembler.c:482:8: warning: implicit conversion from enumeration type 'enum sh_insn' to different enumeration type 'sh_reg' [-Wenum-conversion]
                {10, SH_INS_SYNCO, -(ISA_SH4A), none},
arch/SH/SHDisassembler.c:481:7: warning: implicit conversion from enumeration type 'enum sh_insn' to different enumeration type 'sh_reg' [-Wenum-conversion]
                {7, SH_INS_RTV_N, -(ISA_SH2A), none},
arch/SH/SHDisassembler.c:480:7: warning: implicit conversion from enumeration type 'enum sh_insn' to different enumeration type 'sh_reg' [-Wenum-conversion]
                {6, SH_INS_RTS_N, -(ISA_SH2A), none},
arch/SH/SHDisassembler.c:479:7: warning: implicit conversion from enumeration type 'enum sh_insn' to different enumeration type 'sh_reg' [-Wenum-conversion]
                {5, SH_INS_RESBANK, -(ISA_SH2A), none},
arch/SH/SHDisassembler.c:478:7: warning: implicit conversion from enumeration type 'enum sh_insn' to different enumeration type 'sh_reg' [-Wenum-conversion]
                {2, SH_INS_RTE, ISA_ALL, none},
arch/SH/SHDisassembler.c:477:7: warning: implicit conversion from enumeration type 'enum sh_insn' to different enumeration type 'sh_reg' [-Wenum-conversion]
                {1, SH_INS_SLEEP, ISA_ALL, none},
arch/SH/SHDisassembler.c:476:7: warning: implicit conversion from enumeration type 'enum sh_insn' to different enumeration type 'sh_reg' [-Wenum-conversion]
                {0, SH_INS_RTS, ISA_ALL, none},
arch/SH/SHDisassembler.c:486:17: warning: implicit conversion from enumeration type 'sh_insn' (aka 'enum sh_insn') to different enumeration type 'enum lookup_type' [-Wenum-conversion]
        sh_insn insn = lookup_insn(list, insn_code, mode);
arch/SH/SHDisassembler.c:187:45: note: expanded from macro 'lookup_insn'
#define lookup_insn(list, no, mode) (lookup(insn, list, no, mode).insn)
arch/SH/SHDisassembler.c:486:17: warning: variable 'insn' is uninitialized when used within its own initialization [-Wuninitialized]
        sh_insn insn = lookup_insn(list, insn_code, mode);
arch/SH/SHDisassembler.c:187:45: note: expanded from macro 'lookup_insn'
#define lookup_insn(list, no, mode) (lookup(insn, list, no, mode).insn)
arch/SH/SHDisassembler.c:597:7: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {0, SH_INS_SHLL, ISA_ALL, none},
arch/SH/SHDisassembler.c:598:7: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {1, SH_INS_DT, ISA_SH2, none},
arch/SH/SHDisassembler.c:599:7: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {2, SH_INS_SHAL, ISA_ALL, none},
arch/SH/SHDisassembler.c:600:7: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {8, SH_INS_MULR, -(ISA_SH2A), none},
arch/SH/SHDisassembler.c:601:8: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {15, SH_INS_MOVMU, -(ISA_SH2A), none},
arch/SH/SHDisassembler.c:602:8: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {-1, SH_INS_INVALID, ISA_ALL, none},
arch/SH/SHDisassembler.c:602:8: warning: implicit conversion from enumeration type 'enum sh_insn' to different enumeration type 'sh_reg' [-Wenum-conversion]
                {-1, SH_INS_INVALID, ISA_ALL, none},
arch/SH/SHDisassembler.c:601:8: warning: implicit conversion from enumeration type 'enum sh_insn' to different enumeration type 'sh_reg' [-Wenum-conversion]
                {15, SH_INS_MOVMU, -(ISA_SH2A), none},
arch/SH/SHDisassembler.c:600:7: warning: implicit conversion from enumeration type 'enum sh_insn' to different enumeration type 'sh_reg' [-Wenum-conversion]
                {8, SH_INS_MULR, -(ISA_SH2A), none},
arch/SH/SHDisassembler.c:599:7: warning: implicit conversion from enumeration type 'enum sh_insn' to different enumeration type 'sh_reg' [-Wenum-conversion]
                {2, SH_INS_SHAL, ISA_ALL, none},
arch/SH/SHDisassembler.c:598:7: warning: implicit conversion from enumeration type 'enum sh_insn' to different enumeration type 'sh_reg' [-Wenum-conversion]
                {1, SH_INS_DT, ISA_SH2, none},
arch/SH/SHDisassembler.c:597:7: warning: implicit conversion from enumeration type 'enum sh_insn' to different enumeration type 'sh_reg' [-Wenum-conversion]
                {0, SH_INS_SHLL, ISA_ALL, none},
arch/SH/SHDisassembler.c:604:17: warning: implicit conversion from enumeration type 'sh_insn' (aka 'enum sh_insn') to different enumeration type 'enum lookup_type' [-Wenum-conversion]
        sh_insn insn = lookup_insn(list, insn_code,mode);
arch/SH/SHDisassembler.c:187:45: note: expanded from macro 'lookup_insn'
#define lookup_insn(list, no, mode) (lookup(insn, list, no, mode).insn)
arch/SH/SHDisassembler.c:604:17: warning: variable 'insn' is uninitialized when used within its own initialization [-Wuninitialized]
        sh_insn insn = lookup_insn(list, insn_code,mode);
arch/SH/SHDisassembler.c:187:45: note: expanded from macro 'lookup_insn'
#define lookup_insn(list, no, mode) (lookup(insn, list, no, mode).insn)
arch/SH/SHDisassembler.c:633:7: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {0, SH_INS_SHLR, ISA_ALL, none},
arch/SH/SHDisassembler.c:634:7: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {1, SH_INS_CMP_PZ, ISA_ALL, none},
arch/SH/SHDisassembler.c:635:7: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {2, SH_INS_SHAR, ISA_ALL, none},
arch/SH/SHDisassembler.c:636:7: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {8, SH_INS_CLIPU, -(ISA_SH2A), none},
arch/SH/SHDisassembler.c:637:7: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {9, SH_INS_CLIPS, -(ISA_SH2A), none},
arch/SH/SHDisassembler.c:638:8: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {14, SH_INS_STBANK, -(ISA_SH2A), none},
arch/SH/SHDisassembler.c:639:8: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {15, SH_INS_MOVML, -(ISA_SH2A), none},
arch/SH/SHDisassembler.c:640:8: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {-1, SH_INS_INVALID, ISA_ALL, none},
arch/SH/SHDisassembler.c:640:8: warning: implicit conversion from enumeration type 'enum sh_insn' to different enumeration type 'sh_reg' [-Wenum-conversion]
                {-1, SH_INS_INVALID, ISA_ALL, none},
arch/SH/SHDisassembler.c:639:8: warning: implicit conversion from enumeration type 'enum sh_insn' to different enumeration type 'sh_reg' [-Wenum-conversion]
                {15, SH_INS_MOVML, -(ISA_SH2A), none},
arch/SH/SHDisassembler.c:638:8: warning: implicit conversion from enumeration type 'enum sh_insn' to different enumeration type 'sh_reg' [-Wenum-conversion]
                {14, SH_INS_STBANK, -(ISA_SH2A), none},
arch/SH/SHDisassembler.c:637:7: warning: implicit conversion from enumeration type 'enum sh_insn' to different enumeration type 'sh_reg' [-Wenum-conversion]
                {9, SH_INS_CLIPS, -(ISA_SH2A), none},
                    ^~~~~~~~~~~~
arch/SH/SHDisassembler.c:636:7: warning: implicit conversion from enumeration type 'enum sh_insn' to different enumeration type 'sh_reg' [-Wenum-conversion]
                {8, SH_INS_CLIPU, -(ISA_SH2A), none},
                    ^~~~~~~~~~~~
arch/SH/SHDisassembler.c:635:7: warning: implicit conversion from enumeration type 'enum sh_insn' to different enumeration type 'sh_reg' [-Wenum-conversion]
                {2, SH_INS_SHAR, ISA_ALL, none},
                    ^~~~~~~~~~~
arch/SH/SHDisassembler.c:634:7: warning: implicit conversion from enumeration type 'enum sh_insn' to different enumeration type 'sh_reg' [-Wenum-conversion]
                {1, SH_INS_CMP_PZ, ISA_ALL, none},
                    ^~~~~~~~~~~~~
arch/SH/SHDisassembler.c:633:7: warning: implicit conversion from enumeration type 'enum sh_insn' to different enumeration type 'sh_reg' [-Wenum-conversion]
                {0, SH_INS_SHLR, ISA_ALL, none},
                    ^~~~~~~~~~~
arch/SH/SHDisassembler.c:642:17: warning: implicit conversion from enumeration type 'sh_insn' (aka 'enum sh_insn') to different enumeration type 'enum lookup_type' [-Wenum-conversion]
        sh_insn insn = lookup_insn(list, insn_code,mode);
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
arch/SH/SHDisassembler.c:187:45: note: expanded from macro 'lookup_insn'
#define lookup_insn(list, no, mode) (lookup(insn, list, no, mode).insn)
                                     ~~~~~~ ^~~~
arch/SH/SHDisassembler.c:642:17: warning: variable 'insn' is uninitialized when used within its own initialization [-Wuninitialized]
        sh_insn insn = lookup_insn(list, insn_code,mode);
                ~~~~   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
arch/SH/SHDisassembler.c:187:45: note: expanded from macro 'lookup_insn'
#define lookup_insn(list, no, mode) (lookup(insn, list, no, mode).insn)
                                            ^~~~
arch/SH/SHDisassembler.c:698:7: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {0, SH_INS_ROTL, ISA_ALL, none},
                    ^~~~~~~~~~~
                    {          }
arch/SH/SHDisassembler.c:699:7: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {1, SH_INS_SETRC, ISA_ALL, shdsp},
                    ^~~~~~~~~~~~
                    {           }
arch/SH/SHDisassembler.c:700:7: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {2, SH_INS_ROTCL, ISA_ALL, none},
                    ^~~~~~~~~~~~
                    {           }
arch/SH/SHDisassembler.c:701:7: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {3, SH_INS_LDRC, ISA_ALL, shdsp},
                    ^~~~~~~~~~~
                    {          }
arch/SH/SHDisassembler.c:702:7: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {8, SH_INS_DIVU, -(ISA_SH2A), none},
                    ^~~~~~~~~~~
                    {          }
arch/SH/SHDisassembler.c:703:7: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {9, SH_INS_DIVS, -(ISA_SH2A), none},
                    ^~~~~~~~~~~
                    {          }
arch/SH/SHDisassembler.c:704:8: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {15, SH_INS_MOVMU, -(ISA_SH2A), none},
                     ^~~~~~~~~~~~
                     {           }
arch/SH/SHDisassembler.c:705:8: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {-1, SH_INS_INVALID, ISA_ALL, none},
                     ^~~~~~~~~~~~~~
                     {             }
arch/SH/SHDisassembler.c:705:8: warning: implicit conversion from enumeration type 'enum sh_insn' to different enumeration type 'sh_reg' [-Wenum-conversion]
                {-1, SH_INS_INVALID, ISA_ALL, none},
                     ^~~~~~~~~~~~~~
arch/SH/SHDisassembler.c:704:8: warning: implicit conversion from enumeration type 'enum sh_insn' to different enumeration type 'sh_reg' [-Wenum-conversion]
                {15, SH_INS_MOVMU, -(ISA_SH2A), none},
                     ^~~~~~~~~~~~
arch/SH/SHDisassembler.c:703:7: warning: implicit conversion from enumeration type 'enum sh_insn' to different enumeration type 'sh_reg' [-Wenum-conversion]
                {9, SH_INS_DIVS, -(ISA_SH2A), none},
                    ^~~~~~~~~~~
arch/SH/SHDisassembler.c:702:7: warning: implicit conversion from enumeration type 'enum sh_insn' to different enumeration type 'sh_reg' [-Wenum-conversion]
                {8, SH_INS_DIVU, -(ISA_SH2A), none},
                    ^~~~~~~~~~~
arch/SH/SHDisassembler.c:701:7: warning: implicit conversion from enumeration type 'enum sh_insn' to different enumeration type 'sh_reg' [-Wenum-conversion]
                {3, SH_INS_LDRC, ISA_ALL, shdsp},
                    ^~~~~~~~~~~
arch/SH/SHDisassembler.c:700:7: warning: implicit conversion from enumeration type 'enum sh_insn' to different enumeration type 'sh_reg' [-Wenum-conversion]
                {2, SH_INS_ROTCL, ISA_ALL, none},
                    ^~~~~~~~~~~~
arch/SH/SHDisassembler.c:699:7: warning: arch/SH/SHInstPrinter.cimplicit conversion from enumeration type 'enum sh_insn' to different enumeration type 'sh_reg' [-Wenum-conversion]
:149:11:                {1, SH_INS_SETRC, ISA_ALL, shdsp},
                    ^~~~~~~~~~~~
 warning: enumeration values 'SH_OP_DSP_INVALID', 'SH_OP_DSP_REG_PRE', and 'SH_OP_DSP_IMM' not handled in switch [-Wswitch]
                        switch(info->op.operands[xy].dsp.operand[i]) {
                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
arch/SH/SHDisassembler.c:698:7: warning: implicit conversion from enumeration type 'enum sh_insn' to different enumeration type 'sh_reg' [-Wenum-conversion]
                {0, SH_INS_ROTL, ISA_ALL, none},
                    ^~~~~~~~~~~
arch/SH/SHInstPrinter.c:149:11: note: add missing switch cases
                        switch(info->op.operands[xy].dsp.operand[i]) {
                               ^
arch/SH/SHDisassembler.c:707:17: warning: implicit conversion from enumeration type 'sh_insn' (aka 'enum sh_insn') to different enumeration type 'enum lookup_type' [-Wenum-conversion]
        sh_insn insn = lookup_insn(list, insn_code, mode);
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
arch/SH/SHDisassembler.c:187:45: note: expanded from macro 'lookup_insn'
#define lookup_insn(list, no, mode) (lookup(insn, list, no, mode).insn)
                                     ~~~~~~ ^~~~
arch/SH/SHDisassembler.c:707:17: warning: variable 'insn' is uninitialized when used within its own initialization [-Wuninitialized]
        sh_insn insn = lookup_insn(list, insn_code, mode);
                ~~~~   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
arch/SH/SHDisassembler.c:187:45: note: expanded from macro 'lookup_insn'
#define lookup_insn(list, no, mode) (lookup(insn, list, no, mode).insn)
                                            ^~~~
arch/SH/SHDisassembler.c:734:7: warning: arch/SH/SHInstPrinter.c:221:11: warning: enumeration values 'SH_OP_DSP_INVALID' and 'SH_OP_DSP_IMM' not handled in switch [-Wswitch]
                        switch(info->op.operands[0].dsp.operand[i]) {
                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
suggest braces around initialization of subobject [-Wmissing-braces]
                {0, SH_INS_ROTR, ISA_ALL, none},
                    ^~~~~~~~~~~
arch/SH/SHInstPrinter.c                    {          }:
221:11: note: add missing switch cases
                        switch(info->op.operands[0].dsp.operand[i]) {
                               ^
arch/SH/SHDisassembler.c:735:7: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {1, SH_INS_CMP_PL, ISA_ALL, none},
arch/SH/SHDisassembler.c:736:7: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {2, SH_INS_ROTCR, ISA_ALL, none},
arch/SH/SHInstPrinter.c:246:10: warning: enumeration values 'SH_DSP_CC_INVALID' and 'SH_DSP_CC_NONE' not handled in switch [-Wswitch]
arch/SH/SHDisassembler.c:                switch(info->op.operands[2].dsp.cc) {737
:7: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {8, SH_INS_CLIPU, -(ISA_SH2A), none},
arch/SH/SHDisassembler.c:738:7: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {9, SH_INS_CLIPS, -(ISA_SH2A), none},
                    ^~~~~~~~~~~~
                    {           }arch/SH/SHInstPrinter.c
arch/SH/SHDisassembler.c:739:8: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {14, SH_INS_LDBANK, -(ISA_SH2A), none},
                     ^~~~~~~~~~~~~
                     {            }
:246:10: note: add missing switch cases
arch/SH/SHDisassembler.c:740:8                switch(info->op.operands[2].dsp.cc) {:
                        ^
warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {15, SH_INS_MOVML, -(ISA_SH2A), none},
                     ^~~~~~~~~~~~
                     {           }
arch/SH/SHInstPrinter.c:257:11: arch/SH/SHDisassembler.c:741:8: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {-1, SH_INS_INVALID, ISA_ALL, none},
                     ^~~~~~~~~~~~~~
                     {             }
warning: 28 enumeration values not handled in switch: 'SH_INS_DSP_NOP', 'SH_INS_DSP_MOV', 'SH_INS_DSP_PSHL'... [-Wswitch]
arch/SH/SHDisassembler.c:741:8: warning: implicit conversion from enumeration type 'enum sh_insn' to different enumeration type 'sh_reg' [-Wenum-conversion]
                {-1, SH_INS_INVALID, ISA_ALL, none},
                     ^~~~~~~~~~~~~~
arch/SH/SHDisassembler.c:740:8: warning: implicit conversion from enumeration type 'enum sh_insn' to different enumeration type 'sh_reg' [-Wenum-conversion]
                {15, SH_INS_MOVML, -(ISA_SH2A), none},
                     ^~~~~~~~~~~~
arch/SH/SHDisassembler.c:739:8: warning: implicit conversion from enumeration type 'enum sh_insn' to different enumeration type 'sh_reg' [-Wenum-conversion]
                {14, SH_INS_LDBANK, -(ISA_SH2A), none},
                     ^~~~~~~~~~~~~                        switch(info->op.operands[2].dsp.insn) {

                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
arch/SH/SHDisassembler.c:738:7: warning: implicit conversion from enumeration type 'enum sh_insn' to different enumeration type 'sh_reg' [-Wenum-conversion]
arch/SH/SHInstPrinter.c:257:11:                 {9, SH_INS_CLIPS, -(ISA_SH2A), none},note:
                    ^~~~~~~~~~~~
arch/SH/SHDisassembler.c:737:7: warning: implicit conversion from enumeration type 'enum sh_insn' to different enumeration type 'sh_reg' [-Wenum-conversion]
                {8, SH_INS_CLIPU, -(ISA_SH2A), none},
add missing switch cases
                    ^~~~~~~~~~~~
arch/SH/SHDisassembler.c:736:7:                         switch(info->op.operands[2].dsp.insn) {warning: implicit conversion from enumeration type 'enum sh_insn' to different enumeration type 'sh_reg' [-Wenum-conversion]
                {2, SH_INS_ROTCR, ISA_ALL, none},

                    ^~~~~~~~~~~~
arch/SH/SHDisassembler.c:735:7: warning: implicit conversion from enumeration type 'enum sh_insn' to different enumeration type 'sh_reg' [-Wenum-conversion]
                {1, SH_INS_CMP_PL, ISA_ALL, none},
                    ^~~~~~~~~~~~~
arch/SH/SHDisassembler.c:734:7: warning: implicit conversion from enumeration type 'enum sh_insn' to different enumeration type 'sh_reg' [-Wenum-conversion]                               ^
                {0, SH_INS_ROTR, ISA_ALL, none},
                    ^~~~~~~~~~~
arch/SH/SHDisassembler.c:744:
17: warning:   CC      arch/X86/X86IntelInstPrinter.o
implicit conversion from enumeration type 'sh_insn' (aka 'enum sh_insn') to different enumeration type 'enum lookup_type' [-Wenum-conversion]
        sh_insn insn = lookup_insn(list, insn_code,mode);
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
arch/SH/SHDisassembler.c:187:45: note: expanded from macro 'lookup_insn'
#define lookup_insn(list, no, mode) (lookup(insn, list, no, mode).insn)
                                     ~~~~~~ ^~~~
arch/SH/SHDisassembler.c:744:17: warning: variable 'insn' is uninitialized when used within its own initialization [-Wuninitialized]
        sh_insn insn = lookup_insn(list, insn_code,mode);
                ~~~~   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
arch/SH/SHDisassembler.c:187:45: note: expanded from macro 'lookup_insn'
#define lookup_insn(list, no, mode) (lookup(insn, list, no, mode).insn)
                                            ^~~~
arch/SH/SHDisassembler.c:782:15: warning: implicit conversion from enumeration type 'sh_reg' to different enumeration type 'enum lookup_type' [-Wenum-conversion]
        sh_reg reg = lookup_regs(sts_lds_regs, d, mode);
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
arch/SH/SHDisassembler.c:186:45: note: expanded from macro 'lookup_regs'
#define lookup_regs(list, no, mode) (lookup(reg, list, no, mode).reg)
                                     ~~~~~~ ^~~
arch/SH/SHDisassembler.c:782:15: warning: variable 'reg' is uninitialized when used within its own initialization [-Wuninitialized]
        sh_reg reg = lookup_regs(sts_lds_regs, d, mode);
               ~~~   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
arch/SH/SHDisassembler.c:186:45: note: expanded from macro 'lookup_regs'
#define lookup_regs(list, no, mode) (lookup(reg, list, no, mode).reg)
                                            ^~~
arch/SH/SHDisassembler.c:846:7: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {0, SH_INS_SHLR2, ISA_ALL, none},
                    ^~~~~~~~~~~~
                    {           }
arch/SH/SHDisassembler.c:847:7: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {1, SH_INS_SHLR8, ISA_ALL, none},
                    ^~~~~~~~~~~~
                    {           }
arch/SH/SHDisassembler.c:848:7: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {2, SH_INS_SHLR16, ISA_ALL, none},
                    ^~~~~~~~~~~~~
                    {            }
arch/SH/SHDisassembler.c:849:8: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {10, SH_INS_MOVUA, -(ISA_SH4A), none},
                     ^~~~~~~~~~~~
                     {           }
arch/SH/SHDisassembler.c:850:8: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {14, SH_INS_MOVUA, -(ISA_SH4A), none},
                     ^~~~~~~~~~~~
                     {           }
arch/SH/SHDisassembler.c:851:8: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {-1, SH_INS_INVALID, ISA_ALL, none},
                     ^~~~~~~~~~~~~~
                     {             }
arch/SH/SHDisassembler.c:851:8: warning: implicit conversion from enumeration type 'enum sh_insn' to different enumeration type 'sh_reg' [-Wenum-conversion]
                {-1, SH_INS_INVALID, ISA_ALL, none},
                     ^~~~~~~~~~~~~~
arch/SH/SHDisassembler.c:850:8: warning: implicit conversion from enumeration type 'enum sh_insn' to different enumeration type 'sh_reg' [-Wenum-conversion]
                {14, SH_INS_MOVUA, -(ISA_SH4A), none},
                     ^~~~~~~~~~~~
arch/SH/SHDisassembler.c:849:8: warning: implicit conversion from enumeration type 'enum sh_insn' to different enumeration type 'sh_reg' [-Wenum-conversion]
                {10, SH_INS_MOVUA, -(ISA_SH4A), none},
arch/SH/SHDisassembler.c:848:7: warning: implicit conversion from enumeration type 'enum sh_insn' to different enumeration type 'sh_reg' [-Wenum-conversion]
                {2, SH_INS_SHLR16, ISA_ALL, none},
arch/SH/SHDisassembler.c:847:7: warning: implicit conversion from enumeration type 'enum sh_insn' to different enumeration type 'sh_reg' [-Wenum-conversion]
                {1, SH_INS_SHLR8, ISA_ALL, none},
arch/SH/SHDisassembler.c:846:7: warning: implicit conversion from enumeration type 'enum sh_insn' to different enumeration type 'sh_reg' [-Wenum-conversion]
                {0, SH_INS_SHLR2, ISA_ALL, none},
arch/SH/SHDisassembler.c:854:17: warning: implicit conversion from enumeration type 'sh_insn' (aka 'enum sh_insn') to different enumeration type 'enum lookup_type' [-Wenum-conversion]
        sh_insn insn = lookup_insn(list, op, mode);
arch/SH/SHDisassembler.c:187:45: note: expanded from macro 'lookup_insn'
#define lookup_insn(list, no, mode) (lookup(insn, list, no, mode).insn)
arch/SH/SHDisassembler.c:854:17: warning: variable 'insn' is uninitialized when used within its own initialization [-Wuninitialized]
        sh_insn insn = lookup_insn(list, op, mode);
arch/SH/SHDisassembler.c:187:45: note: expanded from macro 'lookup_insn'
#define lookup_insn(list, no, mode) (lookup(insn, list, no, mode).insn)
arch/SH/SHDisassembler.c:889:7: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {0, SH_INS_JSR, ISA_ALL, none},
arch/SH/SHDisassembler.c:890:7: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {1, SH_INS_TAS, ISA_ALL, none},
arch/SH/SHDisassembler.c:891:7: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {2, SH_INS_JMP, ISA_ALL, none},
arch/SH/SHDisassembler.c:892:7: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {4, SH_INS_JSR_N, -(ISA_SH2A), none},
arch/SH/SHDisassembler.c:893:7: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {8, SH_INS_MOV, -(ISA_SH2A), none},
arch/SH/SHDisassembler.c:894:7: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {9, SH_INS_MOV, -(ISA_SH2A), none},
arch/SH/SHDisassembler.c:895:8: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {10, SH_INS_MOV, -(ISA_SH2A), none},
arch/SH/SHDisassembler.c:896:8: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {12, SH_INS_MOV, -(ISA_SH2A), none},
arch/SH/SHDisassembler.c:897:8: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {13, SH_INS_MOV, -(ISA_SH2A), none},
arch/SH/SHDisassembler.c:898:8: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {14, SH_INS_MOV, -(ISA_SH2A), none},
arch/SH/SHDisassembler.c:899:8: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {-1, SH_INS_INVALID, ISA_ALL, none},
arch/SH/SHDisassembler.c:899:8: warning: implicit conversion from enumeration type 'enum sh_insn' to different enumeration type 'sh_reg' [-Wenum-conversion]
                {-1, SH_INS_INVALID, ISA_ALL, none},
arch/SH/SHDisassembler.c:898:8: warning: implicit conversion from enumeration type 'enum sh_insn' to different enumeration type 'sh_reg' [-Wenum-conversion]
                {14, SH_INS_MOV, -(ISA_SH2A), none},
arch/SH/SHDisassembler.c:897:8: warning: implicit conversion from enumeration type 'enum sh_insn' to different enumeration type 'sh_reg' [-Wenum-conversion]
                {13, SH_INS_MOV, -(ISA_SH2A), none},
arch/SH/SHDisassembler.c:896:8: warning: implicit conversion from enumeration type 'enum sh_insn' to different enumeration type 'sh_reg' [-Wenum-conversion]
                {12, SH_INS_MOV, -(ISA_SH2A), none},
arch/SH/SHDisassembler.c:895:8: warning: implicit conversion from enumeration type 'enum sh_insn' to different enumeration type 'sh_reg' [-Wenum-conversion]
                {10, SH_INS_MOV, -(ISA_SH2A), none},
arch/SH/SHDisassembler.c:894:7: warning: implicit conversion from enumeration type 'enum sh_insn' to different enumeration type 'sh_reg' [-Wenum-conversion]
                {9, SH_INS_MOV, -(ISA_SH2A), none},
arch/SH/SHDisassembler.c:893:7: warning: implicit conversion from enumeration type 'enum sh_insn' to different enumeration type 'sh_reg' [-Wenum-conversion]
                {8, SH_INS_MOV, -(ISA_SH2A), none},
arch/SH/SHDisassembler.c:892:7: warning: implicit conversion from enumeration type 'enum sh_insn' to different enumeration type 'sh_reg' [-Wenum-conversion]
                {4, SH_INS_JSR_N, -(ISA_SH2A), none},
arch/SH/SHDisassembler.c:891:7: warning: implicit conversion from enumeration type 'enum sh_insn' to different enumeration type 'sh_reg' [-Wenum-conversion]
                {2, SH_INS_JMP, ISA_ALL, none},
arch/SH/SHDisassembler.c:890:7: warning: implicit conversion from enumeration type 'enum sh_insn' to different enumeration type 'sh_reg' [-Wenum-conversion]
                {1, SH_INS_TAS, ISA_ALL, none},
arch/SH/SHDisassembler.c:889:7: warning: implicit conversion from enumeration type 'enum sh_insn' to different enumeration type 'sh_reg' [-Wenum-conversion]
                {0, SH_INS_JSR, ISA_ALL, none},
arch/SH/SHDisassembler.c:901:17: warning: implicit conversion from enumeration type 'sh_insn' (aka 'enum sh_insn') to different enumeration type 'enum lookup_type' [-Wenum-conversion]
        sh_insn insn = lookup_insn(list, insn_code, mode);
arch/SH/SHDisassembler.c:187:45: note: expanded from macro 'lookup_insn'
#define lookup_insn(list, no, mode) (lookup(insn, list, no, mode).insn)
arch/SH/SHDisassembler.c:901:17: warning: variable 'insn' is uninitialized when used within its own initialization [-Wuninitialized]
        sh_insn insn = lookup_insn(list, insn_code, mode);
arch/SH/SHDisassembler.c:187:45: note: expanded from macro 'lookup_insn'
#define lookup_insn(list, no, mode) (lookup(insn, list, no, mode).insn)
arch/SH/SHDisassembler.c:1334:7: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {0, SH_INS_FSTS, ISA_ALL, shfpu},
arch/SH/SHDisassembler.c:1335:7: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {1, SH_INS_FLDS, ISA_ALL, shfpu},
arch/SH/SHDisassembler.c:1336:7: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {2, SH_INS_FLOAT, ISA_ALL, shfpu},
arch/SH/SHDisassembler.c:1337:7: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {3, SH_INS_FTRC, ISA_ALL, shfpu},
arch/SH/SHDisassembler.c:1338:7: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {4, SH_INS_FNEG, ISA_ALL, shfpu},
arch/SH/SHDisassembler.c:1339:7: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {5, SH_INS_FABS, ISA_ALL, shfpu},
arch/SH/SHDisassembler.c:1340:7: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {6, SH_INS_FSQRT, ISA_ALL, shfpu},
arch/SH/SHDisassembler.c:1341:7: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {7, SH_INS_FSRRA, ISA_ALL, shfpu},
arch/SH/SHDisassembler.c:1342:7: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {8, SH_INS_FLDI0, ISA_ALL, shfpu},
arch/SH/SHDisassembler.c:1343:7: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {9, SH_INS_FLDI1, ISA_ALL, shfpu},
arch/SH/SHDisassembler.c:1344:8: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {10, SH_INS_FCNVSD, ISA_SH4A, shfpu},
arch/SH/SHDisassembler.c:1345:8: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {11, SH_INS_FCNVDS, ISA_SH4A, shfpu},
arch/SH/SHDisassembler.c:1346:8: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {14, SH_INS_FIPR, ISA_SH4A, shfpu},
arch/SH/SHDisassembler.c:1347:8: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                {-1, SH_INS_INVALID, ISA_ALL, none},
arch/SH/SHDisassembler.c:1347:8: warning: implicit conversion from enumeration type 'enum sh_insn' to different enumeration type 'sh_reg' [-Wenum-conversion]
                {-1, SH_INS_INVALID, ISA_ALL, none},
arch/SH/SHDisassembler.c:1346:8: warning: implicit conversion from enumeration type 'enum sh_insn' to different enumeration type 'sh_reg' [-Wenum-conversion]
                {14, SH_INS_FIPR, ISA_SH4A, shfpu},
arch/SH/SHDisassembler.c:1345:8: warning: implicit conversion from enumeration type 'enum sh_insn' to different enumeration type 'sh_reg' [-Wenum-conversion]
                {11, SH_INS_FCNVDS, ISA_SH4A, shfpu},
arch/SH/SHDisassembler.c:1344:8: warning: implicit conversion from enumeration type 'enum sh_insn' to different enumeration type 'sh_reg' [-Wenum-conversion]
                {10, SH_INS_FCNVSD, ISA_SH4A, shfpu},
arch/SH/SHDisassembler.c:1343:7: warning: implicit conversion from enumeration type 'enum sh_insn' to different enumeration type 'sh_reg' [-Wenum-conversion]
                {9, SH_INS_FLDI1, ISA_ALL, shfpu},
arch/SH/SHDisassembler.c:1342:7: warning: implicit conversion from enumeration type 'enum sh_insn' to different enumeration type 'sh_reg' [-Wenum-conversion]
                {8, SH_INS_FLDI0, ISA_ALL, shfpu},
arch/SH/SHDisassembler.c:1341:7: warning: implicit conversion from enumeration type 'enum sh_insn' to different enumeration type 'sh_reg' [-Wenum-conversion]
                {7, SH_INS_FSRRA, ISA_ALL, shfpu},
arch/SH/SHDisassembler.c:1340:7: warning: implicit conversion from enumeration type 'enum sh_insn' to different enumeration type 'sh_reg' [-Wenum-conversion]
                {6, SH_INS_FSQRT, ISA_ALL, shfpu},
arch/SH/SHDisassembler.c:1339:7: warning: implicit conversion from enumeration type 'enum sh_insn' to different enumeration type 'sh_reg' [-Wenum-conversion]
                {5, SH_INS_FABS, ISA_ALL, shfpu},
arch/SH/SHDisassembler.c:1338:7: warning: implicit conversion from enumeration type 'enum sh_insn' to different enumeration type 'sh_reg' [-Wenum-conversion]
                {4, SH_INS_FNEG, ISA_ALL, shfpu},
arch/SH/SHDisassembler.c:1337:7: warning: implicit conversion from enumeration type 'enum sh_insn' to different enumeration type 'sh_reg' [-Wenum-conversion]
                {3, SH_INS_FTRC, ISA_ALL, shfpu},
arch/SH/SHDisassembler.c:1336:7: warning: implicit conversion from enumeration type 'enum sh_insn' to different enumeration type 'sh_reg' [-Wenum-conversion]
                {2, SH_INS_FLOAT, ISA_ALL, shfpu},
arch/SH/SHDisassembler.c:1335:7: warning: implicit conversion from enumeration type 'enum sh_insn' to different enumeration type 'sh_reg' [-Wenum-conversion]
                {1, SH_INS_FLDS, ISA_ALL, shfpu},
arch/SH/SHDisassembler.c:1334:7: warning: implicit conversion from enumeration type 'enum sh_insn' to different enumeration type 'sh_reg' [-Wenum-conversion]
                {0, SH_INS_FSTS, ISA_ALL, shfpu},
arch/SH/SHDisassembler.c:1352:9: warning: implicit conversion from enumeration type 'sh_insn' (aka 'enum sh_insn') to different enumeration type 'enum lookup_type' [-Wenum-conversion]
        insn = lookup_insn(list, (code >> 4) & 0x0f, mode);
arch/SH/SHDisassembler.c:187:45: note: expanded from macro 'lookup_insn'
#define lookup_insn(list, no, mode) (lookup(insn, list, no, mode).insn)
arch/SH/SHDisassembler.c:1749:35: warning: implicit conversion from enumeration type 'sh_insn' (aka 'enum sh_insn') to different enumeration type 'sh_dsp_insn' (aka 'enum sh_dsp_insn') [-Wenum-conversion]
                info->op.operands[2].dsp.insn = insn;
arch/SH/SHDisassembler.c:1752:36: warning: implicit conversion from enumeration type 'sh_insn' (aka 'enum sh_insn') to different enumeration type 'sh_dsp_insn' (aka 'enum sh_dsp_insn') [-Wenum-conversion]
                        info->op.operands[2].dsp.insn = insn2;
arch/SH/SHDisassembler.c:1773:34: warning: implicit conversion from enumeration type 'sh_insn' (aka 'enum sh_insn') to different enumeration type 'sh_dsp_insn' (aka 'enum sh_dsp_insn') [-Wenum-conversion]
        info->op.operands[2].dsp.insn = insn;
arch/SH/SHDisassembler.c:1784:34: warning: implicit conversion from enumeration type 'sh_insn' (aka 'enum sh_insn') to different enumeration type 'sh_dsp_insn' (aka 'enum sh_dsp_insn') [-Wenum-conversion]
        info->op.operands[2].dsp.insn = insn;
arch/SH/SHDisassembler.c:1809:28: warning: implicit conversion from enumeration type 'enum sh_dsp_insn_type' to different enumeration type 'sh_insn' (aka 'enum sh_insn') [-Wenum-conversion]
                                      SH_INS_DSP_PSHL, SH_INS_DSP_INVALID,
arch/SH/SHDisassembler.c:1809:11: warning: implicit conversion from enumeration type 'enum sh_dsp_insn' to different enumeration type 'sh_insn' (aka 'enum sh_insn') [-Wenum-conversion]
                                      SH_INS_DSP_PSHL, SH_INS_DSP_INVALID,
arch/SH/SHDisassembler.c:1821:12: warning: implicit conversion from enumeration type 'enum sh_dsp_insn_type' to different enumeration type 'sh_insn' (aka 'enum sh_insn') [-Wenum-conversion]
                                              SH_INS_DSP_INVALID, detail);
arch/SH/SHDisassembler.c:1820:12: warning: implicit conversion from enumeration type 'enum sh_dsp_insn' to different enumeration type 'sh_insn' (aka 'enum sh_insn') [-Wenum-conversion]
                                              SH_INS_DSP_PSUBr,
arch/SH/SHDisassembler.c:1834:13: warning: implicit conversion from enumeration type 'enum sh_dsp_insn' to different enumeration type 'sh_insn' (aka 'enum sh_insn') [-Wenum-conversion]
                                                      SH_INS_DSP_PDEC,
arch/SH/SHDisassembler.c:1839:13: warning: implicit conversion from enumeration type 'enum sh_dsp_insn' to different enumeration type 'sh_insn' (aka 'enum sh_insn') [-Wenum-conversion]
                                               SH_INS_DSP_PABS,
arch/SH/SHDisassembler.c:1855:28: warning: implicit conversion from enumeration type 'enum sh_dsp_insn_type' to different enumeration type 'sh_insn' (aka 'enum sh_insn') [-Wenum-conversion]
                                      SH_INS_DSP_PSHA, SH_INS_DSP_INVALID,
  CC      arch/X86/X86ATTInstPrinter.o
arch/SH/SHDisassembler.c:1855:11: warning: implicit conversion from enumeration type 'enum sh_dsp_insn' to different enumeration type 'sh_insn' (aka 'enum sh_insn') [-Wenum-conversion]
                                      SH_INS_DSP_PSHA, SH_INS_DSP_INVALID,
arch/SH/SHDisassembler.c:1859:28: warning: implicit conversion from enumeration type 'enum sh_dsp_insn_type' to different enumeration type 'sh_insn' (aka 'enum sh_insn') [-Wenum-conversion]
                                      SH_INS_DSP_PAND, SH_INS_DSP_INVALID,
arch/SH/SHDisassembler.c:1859:11: warning: implicit conversion from enumeration type 'enum sh_dsp_insn' to different enumeration type 'sh_insn' (aka 'enum sh_insn') [-Wenum-conversion]
                                      SH_INS_DSP_PAND, SH_INS_DSP_INVALID,
arch/SH/SHDisassembler.c:1872:13: warning: implicit conversion from enumeration type 'enum sh_dsp_insn' to different enumeration type 'sh_insn' (aka 'enum sh_insn') [-Wenum-conversion]
                                                      SH_INS_DSP_PINC,
arch/SH/SHDisassembler.c:1877:13: warning: implicit conversion from enumeration type 'enum sh_dsp_insn' to different enumeration type 'sh_insn' (aka 'enum sh_insn') [-Wenum-conversion]
                                               SH_INS_DSP_PRND,
arch/SH/SHDisassembler.c:1886:12: warning: implicit conversion from enumeration type 'enum sh_dsp_insn' to different enumeration type 'sh_insn' (aka 'enum sh_insn') [-Wenum-conversion]
                                              SH_INS_DSP_PDMSB,
arch/SH/SHDisassembler.c:1890:12: warning: implicit conversion from enumeration type 'enum sh_dsp_insn' to different enumeration type 'sh_insn' (aka 'enum sh_insn') [-Wenum-conversion]
                                              SH_INS_DSP_PSWAP,
arch/SH/SHDisassembler.c:1897:28: warning: implicit conversion from enumeration type 'enum sh_dsp_insn' to different enumeration type 'sh_insn' (aka 'enum sh_insn') [-Wenum-conversion]
                                      SH_INS_DSP_PSUB, SH_INS_DSP_PSUBC,
arch/SH/SHDisassembler.c:1897:11: warning: implicit conversion from enumeration type 'enum sh_dsp_insn' to different enumeration type 'sh_insn' (aka 'enum sh_insn') [-Wenum-conversion]
                                      SH_INS_DSP_PSUB, SH_INS_DSP_PSUBC,
arch/SH/SHDisassembler.c:1901:28: warning: implicit conversion from enumeration type 'enum sh_dsp_insn' to different enumeration type 'sh_insn' (aka 'enum sh_insn') [-Wenum-conversion]
                                      SH_INS_DSP_PXOR, SH_INS_DSP_PWSB,
arch/SH/SHDisassembler.c:1901:11: warning: implicit conversion from enumeration type 'enum sh_dsp_insn' to different enumeration type 'sh_insn' (aka 'enum sh_insn') [-Wenum-conversion]
                                      SH_INS_DSP_PXOR, SH_INS_DSP_PWSB,
arch/SH/SHDisassembler.c:1914:13: warning: implicit conversion from enumeration type 'enum sh_dsp_insn' to different enumeration type 'sh_insn' (aka 'enum sh_insn') [-Wenum-conversion]
                                                      SH_INS_DSP_PDEC,
arch/SH/SHDisassembler.c:1919:12: warning: implicit conversion from enumeration type 'enum sh_dsp_insn' to different enumeration type 'sh_insn' (aka 'enum sh_insn') [-Wenum-conversion]
                                              SH_INS_DSP_PABS,
arch/SH/SHDisassembler.c:1936:12: warning: implicit conversion from enumeration type 'enum sh_dsp_insn_type' to different enumeration type 'sh_insn' (aka 'enum sh_insn') [-Wenum-conversion]
                                              SH_INS_DSP_INVALID, detail);
arch/SH/SHDisassembler.c:1935:12: warning: implicit conversion from enumeration type 'enum sh_dsp_insn' to different enumeration type 'sh_insn' (aka 'enum sh_insn') [-Wenum-conversion]
                                              SH_INS_DSP_PADD,
arch/SH/SHDisassembler.c:1940:27: warning: implicit conversion from enumeration type 'enum sh_dsp_insn' to different enumeration type 'sh_insn' (aka 'enum sh_insn') [-Wenum-conversion]
                                      SH_INS_DSP_POR, SH_INS_DSP_PWAD,
arch/SH/SHDisassembler.c:1940:11: warning: implicit conversion from enumeration type 'enum sh_dsp_insn' to different enumeration type 'sh_insn' (aka 'enum sh_insn') [-Wenum-conversion]
                                      SH_INS_DSP_POR, SH_INS_DSP_PWAD,
arch/SH/SHDisassembler.c:1955:13: warning: implicit conversion from enumeration type 'enum sh_dsp_insn' to different enumeration type 'sh_insn' (aka 'enum sh_insn') [-Wenum-conversion]
                                                      SH_INS_DSP_PINC,
arch/SH/SHDisassembler.c:1959:13: warning: implicit conversion from enumeration type 'enum sh_dsp_insn' to different enumeration type 'sh_insn' (aka 'enum sh_insn') [-Wenum-conversion]
                                                      SH_INS_DSP_PRND,
arch/SH/SHDisassembler.c:1969:12: warning: implicit conversion from enumeration type 'enum sh_dsp_insn' to different enumeration type 'sh_insn' (aka 'enum sh_insn') [-Wenum-conversion]
                                              SH_INS_DSP_PDMSB,
arch/SH/SHDisassembler.c:1973:12: warning: implicit conversion from enumeration type 'enum sh_dsp_insn' to different enumeration type 'sh_insn' (aka 'enum sh_insn') [-Wenum-conversion]
                                              SH_INS_DSP_PSWAP,
arch/SH/SHDisassembler.c:1980:11: warning: implicit conversion from enumeration type 'enum sh_dsp_insn' to different enumeration type 'sh_insn' (aka 'enum sh_insn') [-Wenum-conversion]
                                      SH_INS_DSP_PNEG, f_sx, 6, detail);
arch/SH/SHDisassembler.c:1997:11: warning: implicit conversion from enumeration type 'enum sh_dsp_insn' to different enumeration type 'sh_insn' (aka 'enum sh_insn') [-Wenum-conversion]
                                      SH_INS_DSP_PCOPY, f_sx, 6, detail);
arch/SH/SHDisassembler.c:2000:11: warning: implicit conversion from enumeration type 'enum sh_dsp_insn' to different enumeration type 'sh_insn' (aka 'enum sh_insn') [-Wenum-conversion]
                                      SH_INS_DSP_PNEG, f_sy, 4, detail);
arch/SH/SHDisassembler.c:2017:37: warning: implicit conversion from enumeration type 'enum sh_dsp_insn' to different enumeration type 'sh_insn' (aka 'enum sh_insn') [-Wenum-conversion]
                return dsp_op_cc_2opr(code, info, SH_INS_DSP_PCOPY, f_sy, 4, detail);
```

### PR DESCRIPTION
**Pull request by Rot127**
fixes #2010

But we should really look into refactoring it. The fix simply casts explicitly a bunch of enum values. Before that they were implicit.
I know nothing about SH, so can't judge if the enum casting is intended for architectural reasons.

### CODE REVIEW

File: arch/SH/SHDisassembler.c [hunk 1]
```diff
@@ -1937,13 +1957,13 @@ static bool decode_dsp_3op(const uint32_t code, sh_info *info,
 		}
 	case 0x0d:
 		return dsp_op_cc_3opr(code, info,
-				      SH_INS_DSP_POR, SH_INS_DSP_PWAD,
-				      detail);
+								SH_INS_DSP_POR, (sh_dsp_insn_type) SH_INS_DSP_PWAD,
```
Comment (aquynh) [inline arch/SH/SHDisassembler.c]: the indentation is wrong here?

**Review by XVilka — APPROVED** [review]

**Comment by kabeor** [comment]
Thanks! Merged.
