### PR TITLE
RISCV: Fix operand detection (REAL/ALIAS)

### LINKED ISSUE #2896: RISCV cstool flags "ALIAS" operand set as  "REAL".
### Work environment

| Questions                                | Answers
|------------------------------------------|--------------------
| System Capstone runs on OS/arch/bits     | Debian arm 64, MacOS AArch64, MacOS x86, Windows x86 etc.
| Capstone module affected                 | ppc, x86, arm, aarch64 etc.
| Source of Capstone                       | `git clone`, brew, pip, release binaries etc.
| Version/git commit                       | v5.0.1, <commit hash>

### Expected behavior

`cstool` prints "ALIAS" if the alias operand set is shown.
And "REAL" if the real instruction operand set is shown.

### Actual behavior

It doesn't print "ALIAS" for the following RISCV instruction:

```
cstool -d riscv64 67800000
 0  67 80 00 00  ret	
	ID: 31 (jalr)
	Is alias: 1698 (ret) with REAL operand set

	Groups: jump 
```

### Steps to reproduce the behavior

- Use code markdown `CODE` to make your code visible

### Additional Logs, screenshots, source code,  configuration dump, ...

Drag and drop zip archives containing the Additional info here, don't use external services or link.
Screenshots can be directly dropped here.

### PR DESCRIPTION
**Pull request by slate5**
**Your checklist for this pull request**
- [ ] I've documented or updated the documentation of every API function and struct this PR changes.
- [x] I've added tests that prove my fix is effective or that my feature works (if possible)

**Detailed description**

Fixing issue #2896

Also adding a new expected field (uses_alias_details) to `cstest`.

**Test plan**

```
cstool -d riscv64 67800000
 0  67 80 00 00  ret	
	ID: 31 (jalr)
	Is alias: 1698 (ret) with ALIAS operand set

	Groups: jump 

cstool -dr riscv64 67800000
 0  67 80 00 00  ret	
	ID: 31 (jalr)
	Is alias: 1698 (ret) with REAL operand set
	op_count: 3
		operands[0].type: REG = zero
		operands[0].access: WRITE
		operands[1].type: REG = ra
		operands[1].access: READ
		operands[2].type: IMM = 0x0
		operands[2].access: READ

	Groups: ret 
```

**Closing issues**

closes #2896

### CODE REVIEW

File: suite/cstest/src/test_case.c [hunk 1]
```diff
@@ -273,6 +274,19 @@ void test_expected_compare(csh *handle, TestExpected *expected, cs_insn *insns,
...
+					CS_TEST_FAIL(
+						"should use alias operands");
+				}
+			} else {
+				if (insns[i].usesAliasDetails) {
+					CS_TEST_FAIL(
+						"should not use alias operands");
+				}
+			}
+		}
```
Comment (Rot127) [inline suite/cstest/src/test_case.c:289]: We should really add a macro for this check.

**Review by Rot127 — APPROVED** [review]
Thanks for the test extension!

File: suite/cstest/src/test_case.c (hunk 1 above)
Comment (slate5) [reply suite/cstest/src/test_case.c:289]: If you want, it's not a problem for me to add it.

**Comment by moste00** [comment]
LGTM
